// Fallback GIF URLs from hasaneyldrm/exercises-dataset (open fitness dataset on GitHub, served via jsDelivr).
// Used when exercises.gif_url is null in the database.

const FALLBACK: Record<string, string> = {
  "Barbell Bench Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0025-EIeI8Vf.gif",
  "Incline Barbell Bench Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0047-3TZduzM.gif",
  "Dumbbell Bench Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0289-SpYC0Kp.gif",
  "Incline Dumbbell Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/3545-TVdivgY.gif",
  "Decline Bench Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0033-GrO65fd.gif",
  "Overhead Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0091-kTbSH9h.gif",
  "Dumbbell Shoulder Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0361-84RyJf8.gif",
  "Arnold Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/2137-Xy4jlWA.gif",
  "Lateral Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0012-UGhRD1A.gif",
  "Front Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0977-sTg7iys.gif",
  "Deadlift": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1009-kuMiR2T.gif",
  "Romanian Deadlift": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0085-wQ2c4XD.gif",
  "Pull Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0652-lBDjFxJ.gif",
  "Lat Pulldown": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0579-7F1DVzn.gif",
  "Barbell Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0027-eZyBC3j.gif",
  "Dumbbell Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0293-BJ0Hz5L.gif",
  "Seated Cable Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0159-kesXOpB.gif",
  "Face Pull": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0970-r1XNRYB.gif",
  "Barbell Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0031-25GPyDY.gif",
  "Dumbbell Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0285-BU15nH4.gif",
  "Back Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0043-qXTaZnJ.gif",
  "Front Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0042-zG0zs85.gif",
  "Goblet Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1760-yn8yg1r.gif",
  "Leg Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/2287-V07qpXy.gif",
  "Walking Lunge": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1410-py1HSzx.gif",
  "Bulgarian Split Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0410-qx4fgX7.gif",
  "Leg Extension": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0585-my33uHU.gif",
  "Leg Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1770-sJFIDIp.gif",
  "Hip Thrust": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0058-SNFfUff.gif",
  "Calf Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0999-9JprnPh.gif",
  "Plank": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/3544-5VXmnV5.gif",
  "Hanging Leg Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0472-I3tsCnC.gif",
  "Cable Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0175-WW95auq.gif",
  "Russian Twist": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0687-XVDdcoj.gif",
  "Ab Wheel Rollout": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0857-NAgVB3t.gif",
  "Close Grip Bench Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0030-J6Dx1Mu.gif",
  "Dip": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0009-PAgTVaK.gif",
  "Skull Crusher": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0056-HJ63mSO.gif",
  "Tricep Pushdown": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1723-qRZ5S1N.gif",
  "Overhead Cable Extension": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1722-1xHyxys.gif",
  "Pec Deck": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0596-v3xmPAR.gif",
  "Cable Crossover": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1320-UFGF6gk.gif",
  "Dumbbell Fly": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0308-yz9nUhF.gif",
  "Pause Bench Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0025-EIeI8Vf.gif",
  "Landmine Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0025-EIeI8Vf.gif",
  "Upright Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0120-UDlhcO8.gif",
  "Rear Delt Fly": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1022-tc5dYrf.gif",
  "T-Bar Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0027-eZyBC3j.gif",
  "Chest Supported Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0327-7vG5o25.gif",
  "Straight Arm Pulldown": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0238-x69MAlq.gif",
  "Shrugs": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0095-dG7tG5y.gif",
  "Hammer Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0165-HPlPoQA.gif",
  "Preacher Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1627-hacCyUv.gif",
  "Concentration Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0976-kmVVAfu.gif",
  "Incline Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0072-WLvTAv5.gif",
  "Hack Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0046-5VCj6iH.gif",
  "Smith Machine Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1385-IeDEXTe.gif",
  "Sumo Deadlift": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0117-KgI0tqW.gif",
  "Good Morning": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0044-XlZ4lAC.gif",
  "Glute Ham Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/3235-zHEpuuc.gif",
  "Step Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1008-d5bTEPV.gif",
  "Adductor Machine": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0598-oHsrypV.gif",
  "Abductor Machine": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0597-CHpahtl.gif",
  "Nordic Hamstring Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1417-GOJKFfO.gif",
  "Cable Woodchop": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0243-aVs3BR3.gif",
  "Pallof Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0979-9pa4H5m.gif",
  "Side Plank": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/3544-5VXmnV5.gif",
  "Dead Bug": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0276-iny3m5y.gif",
  "Bicycle Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0972-tZkGYZ9.gif",
  "Decline Sit Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0282-QLL2gdc.gif",
  "Push Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0662-I4hDWkc.gif",
  "Diamond Push Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0283-soIB2rj.gif",
  "Pike Push Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1296-sVvXT5J.gif",
  "Inverted Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0499-bZGHsAZ.gif",
  "Muscle Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0631-yJUHKTn.gif",
  "Single Leg RDL": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/2805-daBmy1Y.gif",
  "Trap Bar Deadlift": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0811-jQGwmxN.gif",
  "Box Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0024-Y7YcmIJ.gif",
  "Zercher Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0042-zG0zs85.gif",
  "Pause Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0043-qXTaZnJ.gif",
  "Wrist Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0994-Ezpnw9d.gif",
  "Reverse Wrist Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0994-Ezpnw9d.gif",
  "Farmers Walk": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/2133-qPEzJjA.gif",
  "Suitcase Carry": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/2133-qPEzJjA.gif",
  "Kettlebell Swing": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0549-UHJlbu3.gif",
  "Turkish Get Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0551-Ha7SZ3y.gif",
  "Clean and Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0028-SGY8Zui.gif",
  "Power Clean": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0648-SiWCcTN.gif",
  "Snatch Grip Deadlift": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0032-ila4NZS.gif",
  "Deficit Deadlift": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0032-ila4NZS.gif",
  "Machine Chest Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1301-wDN97Ca.gif",
  "Smith Machine Bench": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1625-yB9SvIF.gif",
  "Shoulder Machine Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0997-peAeMR3.gif",
  "Assisted Pull Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0017-kiJ4Z2K.gif",
  "Cable Lat Prayer": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1724-NN8nSNT.gif",
  "Seal Row": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0027-eZyBC3j.gif",
  "Y Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0011-03lzqwk.gif",
  "T Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0011-03lzqwk.gif",
  "Spider Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0374-mwpPcr1.gif",
  "Drag Curl": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0038-IENzBdA.gif",
  "JM Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0450-hnOYgH3.gif",
  "Floor Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0065-vtusOWT.gif",
  "Svend Press": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0748-trqKQv2.gif",
  "Sissy Squat": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1489-xdYPUtE.gif",
  "Wall Sit": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0624-sVQCCeG.gif",
  "Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0972-tZkGYZ9.gif",
  "Reverse Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0872-nCU1Ekp.gif",
  "Lying Leg Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0012-UGhRD1A.gif",
  "Captain's Chair Leg Raise": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/2963-weoDEpH.gif",
  "Ab Plate Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0832-s8nrDXF.gif",
  "Decline Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0277-9Ap7miY.gif",
  "Rope Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0874-XU3ePuv.gif",
  "V-Up": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0001-2gPfomN.gif",
  "Flutter Kick": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0459-UVo2Qs2.gif",
  "Hollow Hold": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0464-CosupLu.gif",
  "Machine Seated Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0212-8xUv4J7.gif",
  "Standing Cable Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0226-jpgqxiS.gif",
  "Exercise Ball Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1314-qLpO4vV.gif",
  "Oblique Crunch": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/1495-cJgSTmh.gif",
  "Pallof Press with Rotation": "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos/0979-9pa4H5m.gif",
};

export function exerciseGifFallbackUrl(canonicalName: string | null | undefined): string | null {
  if (!canonicalName) return null;
  return FALLBACK[canonicalName] ?? null;
}
