-- Archived curated ~100 exercises (rich aliases). Not executed. See seed.sql.
-- Run after migrations. Inserts ~100 canonical exercises.

insert into public.exercises (canonical_name, aliases, muscle_group, equipment, default_rest_seconds, gif_url) values
('Barbell Bench Press', array['bench press','barbell bench','flat bench press'], 'chest', 'barbell', 75, null),
('Incline Barbell Bench Press', array['incline bench press','incline barbell press'], 'chest', 'barbell', 75, null),
('Dumbbell Bench Press', array['db bench press','dumbbell press'], 'chest', 'dumbbells', 75, null),
('Incline Dumbbell Press', array['incline db press','incline dumbbell press'], 'chest', 'dumbbells', 75, null),
('Decline Bench Press', array['decline barbell press','decline bench'], 'chest', 'barbell', 75, null),
('Overhead Press', array['shoulder press','military press','ohp','standing press'], 'shoulders', 'barbell', 75, null),
('Dumbbell Shoulder Press', array['db shoulder press','seated db press'], 'shoulders', 'dumbbells', 75, null),
('Arnold Press', array['arnold dumbbell press'], 'shoulders', 'dumbbells', 75, null),
('Lateral Raise', array['side raise','dumbbell lateral raise'], 'shoulders', 'dumbbells', 75, null),
('Front Raise', array['dumbbell front raise','plate front raise'], 'shoulders', 'dumbbells', 75, null),
('Deadlift', array['barbell deadlift','conventional deadlift'], 'back', 'barbell', 75, null),
('Romanian Deadlift', array['rdl','single leg rdl'], 'hamstrings', 'barbell', 75, null),
('Pull Up', array['pullups','chin up','chinups','pull-up','chin-up'], 'back', 'bodyweight', 75, null),
('Lat Pulldown', array['pulldown','wide grip pulldown'], 'back', 'machine', 75, null),
('Barbell Row', array['bent over row','bent-over row','barbell bent row','barbell bent-over row','pendlay row'], 'back', 'barbell', 75, null),
('Dumbbell Row', array['one arm row','db row','one-arm dumbbell row'], 'back', 'dumbbells', 75, null),
('Seated Cable Row', array['cable row','low row'], 'back', 'cable', 75, null),
('Face Pull', array['cable face pull'], 'rear delts', 'cable', 75, null),
('Barbell Curl', array['bicep curl','curl','standing barbell curl'], 'biceps', 'barbell', 75, null),
('Dumbbell Curl', array['db curl','alternating curl'], 'biceps', 'dumbbells', 75, null),
('Back Squat', array['barbell squat','squat','high bar squat'], 'quads', 'barbell', 75, null),
('Front Squat', array['front barbell squat'], 'quads', 'barbell', 75, null),
('Goblet Squat', array['db goblet squat','kettlebell goblet squat'], 'quads', 'dumbbells', 75, null),
('Leg Press', array['machine leg press','sled leg press'], 'quads', 'machine', 75, null),
('Walking Lunge', array['lunges','db lunges','forward lunge'], 'legs', 'dumbbells', 75, null),
('Bulgarian Split Squat', array['bss','split squat','rear foot elevated split squat'], 'legs', 'dumbbells', 75, null),
('Leg Extension', array['quad extension'], 'quads', 'machine', 75, null),
('Leg Curl', array['hamstring curl','lying leg curl'], 'hamstrings', 'machine', 75, null),
('Hip Thrust', array['barbell hip thrust'], 'glutes', 'barbell', 75, null),
('Calf Raise', array['standing calf raise','seated calf raise'], 'calves', 'machine', 75, null),
('Plank', array['front plank'], 'core', 'bodyweight', 75, null),
('Hanging Leg Raise', array['leg raise','hanging knees up','toes to bar'], 'abs', 'bodyweight', 75, null),
('Cable Crunch', array['ab crunch cable','kneeling cable crunch'], 'abs', 'cable', 75, null),
('Russian Twist', array['db russian twist','weighted russian twist'], 'core', 'dumbbells', 75, null),
('Ab Wheel Rollout', array['ab rollout','wheel rollout'], 'core', 'ab wheel', 75, null),

('Close Grip Bench Press', array['cgbp','narrow grip bench'], 'triceps', 'barbell', 75, null),
('Dip', array['chest dip','tricep dip','parallel bar dip'], 'chest', 'bodyweight', 75, null),
('Skull Crusher', array['lying tricep extension','ez skull crusher'], 'triceps', 'barbell', 75, null),
('Tricep Pushdown', array['cable pushdown','rope pushdown'], 'triceps', 'cable', 75, null),
('Overhead Cable Extension', array['cable overhead extension'], 'triceps', 'cable', 75, null),
('Pec Deck', array['pec fly machine','machine fly'], 'chest', 'machine', 75, null),
('Cable Crossover', array['cable fly','high cable fly'], 'chest', 'cable', 75, null),
('Dumbbell Fly', array['db fly','flat fly'], 'chest', 'dumbbells', 75, null),
('Pause Bench Press', array['paused bench'], 'chest', 'barbell', 75, null),
('Landmine Press', array['single arm landmine press'], 'shoulders', 'barbell', 75, null),
('Upright Row', array['barbell upright row','cable upright row'], 'shoulders', 'barbell', 75, null),
('Rear Delt Fly', array['reverse fly','bent over reverse fly'], 'rear delts', 'dumbbells', 75, null),
('T-Bar Row', array['chest supported t-bar'], 'back', 'barbell', 75, null),
('Chest Supported Row', array['incline bench row'], 'back', 'dumbbells', 75, null),
('Straight Arm Pulldown', array['lat pushdown'], 'back', 'cable', 75, null),
('Shrugs', array['barbell shrug','dumbbell shrug'], 'traps', 'barbell', 75, null),
('Hammer Curl', array['neutral grip curl','rope hammer'], 'biceps', 'dumbbells', 75, null),
('Preacher Curl', array['ez preacher curl'], 'biceps', 'barbell', 75, null),
('Concentration Curl', array['seated concentration curl'], 'biceps', 'dumbbells', 75, null),
('Incline Curl', array['incline db curl'], 'biceps', 'dumbbells', 75, null),

('Hack Squat', array['machine hack squat'], 'quads', 'machine', 75, null),
('Smith Machine Squat', array['smith squat'], 'quads', 'machine', 75, null),
('Sumo Deadlift', array['wide stance deadlift'], 'glutes', 'barbell', 75, null),
('Good Morning', array['barbell good morning'], 'hamstrings', 'barbell', 75, null),
('Glute Ham Raise', array['ghr'], 'hamstrings', 'machine', 75, null),
('Step Up', array['db step up','box step up'], 'quads', 'dumbbells', 75, null),
('Adductor Machine', array['hip adduction'], 'legs', 'machine', 75, null),
('Abductor Machine', array['hip abduction'], 'glutes', 'machine', 75, null),
('Nordic Hamstring Curl', array['nordic curl'], 'hamstrings', 'bodyweight', 75, null),

('Cable Woodchop', array['wood chop'], 'core', 'cable', 75, null),
('Pallof Press', array['cable pallof press'], 'core', 'cable', 75, null),
('Side Plank', array['lateral plank'], 'core', 'bodyweight', 75, null),
('Dead Bug', array['deadbug'], 'core', 'bodyweight', 75, null),
('Bicycle Crunch', array['bicycle kicks'], 'abs', 'bodyweight', 75, null),
('Decline Sit Up', array['decline crunch'], 'abs', 'bodyweight', 75, null),

('Push Up', array['pushup','press up'], 'chest', 'bodyweight', 75, null),
('Diamond Push Up', array['close grip pushup'], 'triceps', 'bodyweight', 75, null),
('Pike Push Up', array['shoulder pushup'], 'shoulders', 'bodyweight', 75, null),
('Inverted Row', array['bodyweight row','ring row'], 'back', 'bodyweight', 75, null),
('Muscle Up', array['bar muscle up'], 'back', 'bodyweight', 75, null),

('Single Leg RDL', array['one leg rdl','slrdl'], 'hamstrings', 'dumbbells', 75, null),
('Trap Bar Deadlift', array['hex bar deadlift'], 'legs', 'barbell', 75, null),
('Box Squat', array['bench squat'], 'quads', 'barbell', 75, null),
('Zercher Squat', array['zercher'], 'quads', 'barbell', 75, null),
('Pause Squat', array['paused squat'], 'quads', 'barbell', 75, null),

('Wrist Curl', array['forearm curl'], 'forearms', 'barbell', 75, null),
('Reverse Wrist Curl', array['reverse curl forearm'], 'forearms', 'barbell', 75, null),
('Farmers Walk', array['farmer carry','trap bar carry'], 'traps', 'dumbbells', 75, null),
('Suitcase Carry', array['one arm carry'], 'core', 'dumbbells', 75, null),
('Kettlebell Swing', array['kb swing','russian swing'], 'glutes', 'kettlebell', 75, null),
('Turkish Get Up', array['tgu'], 'full body', 'kettlebell', 75, null),
('Clean and Press', array['barbell clean press'], 'full body', 'barbell', 75, null),
('Power Clean', array['hang clean'], 'full body', 'barbell', 75, null),
('Snatch Grip Deadlift', array['wide grip deadlift'], 'back', 'barbell', 75, null),
('Deficit Deadlift', array['deficit pull'], 'back', 'barbell', 75, null),

('Machine Chest Press', array['hammer strength press'], 'chest', 'machine', 75, null),
('Smith Machine Bench', array['smith bench'], 'chest', 'machine', 75, null),
('Shoulder Machine Press', array['machine ohp'], 'shoulders', 'machine', 75, null),
('Assisted Pull Up', array['assisted pullup'], 'back', 'machine', 75, null),
('Cable Lat Prayer', array['lat prayer'], 'back', 'cable', 75, null),
('Seal Row', array['chest supported seal row'], 'back', 'barbell', 75, null),
('Y Raise', array['incline y raise'], 'shoulders', 'dumbbells', 75, null),
('T Raise', array['rear delt t raise'], 'rear delts', 'dumbbells', 75, null),
('Spider Curl', array['prone incline curl'], 'biceps', 'dumbbells', 75, null),
('Drag Curl', array['barbell drag curl'], 'biceps', 'barbell', 75, null),
('JM Press', array['jm bench'], 'triceps', 'barbell', 75, null),
('Floor Press', array['db floor press','barbell floor press'], 'chest', 'barbell', 75, null),
('Svend Press', array['plate press'], 'chest', 'plates', 75, null),
('Sissy Squat', array['bodyweight sissy squat'], 'quads', 'bodyweight', 75, null),
('Wall Sit', array['wall squat hold'], 'quads', 'bodyweight', 75, null),

-- Abs (explicit muscle_group for swap / filtering)
('Crunch', array['abdominal crunch','ab crunch','floor crunch'], 'abs', 'bodyweight', 75, null),
('Reverse Crunch', array['reverse ab crunch'], 'abs', 'bodyweight', 75, null),
('Lying Leg Raise', array['flat leg raise','supine leg raise'], 'abs', 'bodyweight', 75, null),
('Captain''s Chair Leg Raise', array['captains chair','knee raise station','vertical knee raise'], 'abs', 'machine', 75, null),
('Ab Plate Crunch', array['weighted crunch','plate crunch'], 'abs', 'plates', 75, null),
('Decline Crunch', array['decline abdominal','decline ab crunch'], 'abs', 'bodyweight', 75, null),
('Rope Crunch', array['kneeling rope crunch','high pulley crunch'], 'abs', 'cable', 75, null),
('V-Up', array['v up','jackknife'], 'abs', 'bodyweight', 75, null),
('Flutter Kick', array['lying flutter kicks','scissor kicks'], 'abs', 'bodyweight', 75, null),
('Hollow Hold', array['hollow body hold','hollow rock prep'], 'abs', 'bodyweight', 75, null),
('Machine Seated Crunch', array['ab crunch machine','seated ab machine'], 'abs', 'machine', 75, null),
('Standing Cable Crunch', array['standing kneeling cable crunch'], 'abs', 'cable', 75, null),
('Exercise Ball Crunch', array['stability ball crunch','swiss ball crunch'], 'abs', 'stability ball', 75, null),
('Oblique Crunch', array['side crunch','cross body crunch'], 'abs', 'bodyweight', 75, null),
('Pallof Press with Rotation', array['pallof rotation','anti rotation press'], 'abs', 'cable', 75, null);
